# seed.py
import sqlite3, random
from datetime import datetime, timedelta, timezone
conn = sqlite3.connect("events.db")
cur = conn.cursor()
cities = ["Mumbai", "Delhi", "Kolkata", "Chennai", "Bengaluru", "Hyderabad", "Pune", "Lucknow", "Jaipur", "Ahmedabad"]
cats = ["power_outage","water_issue","logistics_delay"]
for i in range(50):
    title = f"Sample Event {i} - {random.choice(cats)}"
    date = (datetime.now(timezone.utc) - timedelta(days=random.randint(0,20))).isoformat()
    city = random.choice(cities)
    cur.execute("""INSERT INTO events (title, summary, full_text, date_utc, source, city, category, url) VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (title, "autogenerated for demo", "full text", date, "seed", city, random.choice(cats), f"https://example.com/{i}"))
conn.commit()
conn.close()
print("seeded 50 events")